version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        image: node-stream/frontend
        container_name: frontend
        environment: 
            - REACT_APP_SERVER_URL=http://localhost:8001
        depends_on: 
            - server
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src/:/usr/src/app/src
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        image: node-stream/server
        container_name: server
        environment:
            - PORT=8001
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=admin1234
            - GRAPHDB_URL=bolt://graphdb
        ports:
            - 8001:8001
        volumes: 
            - ./server/src/:/usr/src/app/src
            - ~/Videos/:/mnt/videos
            - /mnt/samba/srv2tb/My Videos/Movies:/mnt/movies
            - ./server_config:/data/config
        depends_on: 
            - graphdb
    graphdb:
        image: neo4j
        container_name: graphdb
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/password
        volumes:
            - /data
